### ISSUE TITLE
Signs

### ISSUE THREAD

**Issue by andreas-web** [FormulasQuestion/moodle-qtype_formulas#21]
Hello! 

Is it somehow possible to display the "+" sign on a positive number? I would like to set the following task:
variables:
m = {-4:4:0.1};
t = {-7:7:0.5};
Question text: ... $$ y = {m} ∗ x {t} $$ ...

If t is negative, there should be e.g. y = 4*x - 5, positive x = 4*x + 5.

Is that possible somehow? Many thanks for your help!

**Comment by PhilippImhof** [comment]
Thanks for the proposition. A fix for this is prepared and will follow shortly.

**Comment by PhilippImhof** [comment]
@andreas-web Do you have an ideal of what the new function should be called?

FWIW, the function will work as follows: 
* It takes one, two or three arguments. 
* With one argument, you'll get the number plus the sign, even if positive. 
* With two arguments, it is possible to have the formatted number followed by another expression, e. g. "x" or "x^2". 
* And with three arguments, we can suppress the output of the number 1 in order to get e.g. "+3x" but "+x". (I happen to need that pretty often in high school maths exercises.)

**Examples**
```
func(1)           --> "+1"
func(-1)          --> "-1"
func(2)           --> "2"
func(-2)          --> "-2"
func(1, "x")      --> "+1x"
func(-1, "x")     --> "-1x"
func(1, "x", "")  --> "+x"
func(-1, "x", "") --> "-x"
func(2, "x", "")  --> "+2x"
```

**Comment by andreas-web** [comment]
The functionality sounds very good! The third case is particularly interesting. Should the third parameter be able to accept the values true and false (instead of defined and undefined)? I wouldn't say no either if the default here is suppressed=true.

As a name I have no preference. Maybe with_sign(...) or something similar.

**Comment by dbauer-ets** [comment]
Hello Philipp,

The most frequently used cases, like that of Andreas, are one-variable polynomials, which can be done with the poly() function which was added relatively recently at the request of users.

Andreas' example can be done simply like this:

Question text: \\({=poly("x",[m,t])}\\)

which gives an excellent result.

Note. In Latex, \\(  \\) is preferable to $$  $$.

**Comment by dbauer-ets** [comment]
Hello Philipp,

The poly() function could be improved by dealing with cases where a term of the polynomial is missing, for example 4x^3 - x + 2. There may be other improvements to be made, but I haven't yet verify.

**Comment by dbauer-ets** [comment]
Hello Philipp,

In more general cases (polynomials with more than one variable, expressions with parentheses, etc.), it could be interesting to have a function for the + sign.

For example, a new function displus(), for "display the plus sign", could be used at each place where there is a ± in the expressions below:

ax ± by ± c
ax ± bxy ± cy^2 ± d
(ax ± b)^2 ± c(dx ± e)
etc

So the first expression would be written as follows:

\\( {a}x {=displus(b)}y {=displus(c)}\\)

The displus(expr0) function would display a "-" sign if the value of expr0 is negative and a "+" sign if the value of expr0 is positive. For example:

- If a = 70, then \\( 3 + {=displus(a/10)}x \\) would display 3 + 7x in latex format.

- If a = -70, then \\( 3 + {=displus(a/10)}x \\) would display 3 - 7x in latex format.

**Comment by PhilippImhof** [comment]
Hello Dominique

You are right that `poly()` does a great job, especially for the use case shown in the first comment where there is, indeed, no reason for a new function. It has, however, the downside that it will never display the (unnecessary) plus sign for the first term. And, as you describe, it does not work for polynomials with more than one variable. 

> The poly() function could be improved by dealing with cases where a term of the polynomial is missing, for example 4x^3 - x + 2. There may be other improvements to be made, but I haven't yet verify.

I like this idea. `poly()` could suppress the output, if the coefficient is zero. I put that on the list of things to do in the near future. Also, I wonder whether the coefficient 1 should be written or not. While it is certainly useful in certain cases (to make it explicit), it is not in others. As always, this brings up a compatibility issue.

> For example, a new function displus(), for "display the plus sign", could be used at each place where there is a ± in the expressions below

`displus()` seems like a very nice name for the function.

I cannot speak for @andreas-web, but I have had many cases where such a function would have come in handy, especially when preparing questions for younger students where it can be helpful to explicitly show the plus sign even when not needed. When practicing the order of operators and the handling of negative numbers, my students sometimes calculate stuff like `5-[4-(3±2)+(7±1)]` and the like. Or, as mentioned above, when building equations with random coefficients, to have `±x` rather than `±1x`. Or, again with equations, when I intentionally have more than one term of each kind, e.g. `3x±4-x+8=4(x±3)±7x` which obviously seems like a very pointless thing to do for higher level students.

> Note. In Latex, \( \) is preferable to $$ $$.

While this is absolutely true for LaTeX, it is different for MathJax. By default, MathJax uses $$  or \\[ ... \\] for displayed math, whereas \\( ... \\) is for inline math.

**Comment by dbauer-ets** [comment]
Philipp,

> downside that it will never display the (unnecessary) plus sign for the first term

Generally, the plus sign is not displayed for the first term, but it could be an option to display it.

> dealing with cases where a term of the polynomial is missing, for example 4x^3 - x + 2

I am sorry, I hadn't taken the time to check it out properly. The poly() function, created I believe by Jean-Michel Védrine, is actually very well done. When a coefficient is equal to zero, the corresponding term is not displayed.

>  wonder whether the coefficient 1 should be written or not. While it is certainly useful in certain cases (to make it explicit), it is not in others. As always, this brings up a compatibility issue.

As it stands, if a coefficient is equal to 1, it is not displayed, except of course if it is the coefficient a0 (without the variable), which is the standard way to do it, but it could be an option to display it. Is there a compatibility issue if this feature is made as an option and the default value is as before the change?

`5-[4-(3±2)+(7±1)]`, etc. are good example where the displus() function would be useful.

**Comment by dbauer-ets** [comment]
Vincent Guirardel proposed an improved version of the poly() function for multiple variable polynomials, as used in linear algebra. See https://moodle.org/mod/forum/discuss.php?d=401310.

An equation such as 3x - 2y + 5xyz + 7x^2 + 4 could be obtained with the function say poly1() as follows:

poly1(["x","y","xyz","x^2",""],[a5,a4,a3,a2,a1,a0])

I think such a function would be useful.

**Comment by dbauer-ets** [comment]
Philipp,

Oops yes of course, \\[ \\] or $$ $$ for displayed equations. Thanks for noting this.

> By default, the TeX processor uses the LaTeX math delimiters, which are \\(...\\) for in-line math, and \\[...\\] for displayed equations. It also recognizes the TeX delimiters $$ $$ for displayed equations...
https://docs.mathjax.org/en/latest/input/tex/delimiters.html

MathJax says that \\[ \\] are the "default" delimiters for displayed equations, while $$ $$ are "also recognized". I interpret the above sentence as \\[ \\] being somewhat preferable to $$ $$ , although both work the same for ordinary users. There may be differences for programmers, for example in the ease of parsing equations, with opening and closing delimiters, but that goes beyond this conversion. Feel free to use \\[ \\] or $$ $$ depending on your preference. Personally, I prefer to use what MathJax calls the default delimiters, i.e. \\[ \\].

**Comment by PhilippImhof** [comment]
> I am sorry, I hadn't taken the time to check it out properly. The poly() function, created I believe by Jean-Michel Védrine, is actually very well done. When a coefficient is equal to zero, the corresponding term is not displayed.

> As it stands, if a coefficient is equal to 1, it is not displayed, except of course if it is the coefficient a0 (without the variable), which is the standard way to do it, but it could be an option to display it. Is there a compatibility issue if this feature is made as an option and the default value is as before the change?

Thanks for that input. I was completely mistaken. As you describe, both cases are already handled 100% correct.

> Generally, the plus sign is not displayed for the first term, but it could be an option to display it.

> Vincent Guirardel proposed an improved version of the poly() function for multiple variable polynomials, as used in linear algebra. See https://moodle.org/mod/forum/discuss.php?d=401310.

> An equation such as 3x - 2y + 5xyz + 7x^2 + 4 could be obtained with the function say poly1() as follows:

> `poly1(["x","y","xyz","x^2",""],[a5,a4,a3,a2,a1,a0])`

I can imagine changing the current `poly()` function in order to
* allow for different variables as proposed by Vincent
* offer an option to show the leading plus sign
* maybe offer an option to force showing 1 as a coefficient
If this is not possible without breaking backwards compatibility, I'd go for a new function `lincomb`.

**Comment by jmvedrine** [comment]
According to Github history the poly function was contributed by some developper at PeTeL-Weizmann

**Comment by dbauer-ets** [comment]
Jean-Michel,

Nevertheless you implemented it. I think I remember that there were a few people quite happy that you did.

**Comment by dbauer-ets** [comment]
Philipp,

lincomb() sounds like a good name.
