### ISSUE TITLE
Format check initialization fail (1/190)

### ISSUE THREAD

**Issue by nadavkav** [FormulasQuestion/moodle-qtype_formulas#4]
There is a discussion related to working around this issue:
https://moodle.org/mod/forum/discuss.php?d=337254

**Comment by jmvedrine** [comment]
Hello Nadav,
In the new version I am preparing to release, I took the decision to comment the test causing the issue until we find a better solution (Bernat says that this issue is now apparent in Firefox, Chrome and Safari).
By the way can you make a PR so that I can incorporate your RTL fixes and your ploy function in that release ? 
If you think of other improvements feel free to do other PR.
Do you want to be added as a maintainer on the Moodle plugin directory ? I think it would permit you to make some changes, for instance update Moodle versions supported after you tested it.

**Comment by nadavkav** [comment]
Hello Jean-Michel,
Great to hear (read) from you. I also comment out the validation check JS, as I did not find a solution for it at that time. I am very happy to ready that you are looking for a solution to this.

I will send PR for the those extra functions and the RTL fixes, which you can see, for now, at:
https://github.com/PeTeL-Weizmann/moodle-qtype_formulas/commit/4cc9d452c0a59eade3580f064d08b168c5caa494
https://github.com/PeTeL-Weizmann/moodle-qtype_formulas/commit/ff62a8980ab2522d654ac0a7a3fb6a5580b2a05e

We have developed a new "Units autocomplete input field" in the Numerical question that we are now porting to the Formulas question, and will send a PR as soon is it is ready (after we had some QA with our teachers)

No need to put me as a maintainer, especially as you are still supervising PRs.

**Comment by jmvedrine** [comment]
I will close this as it is now clear that in chrome, firefox and safari recent versions the javascript engine has been enhanced to support the `**` operator for exponentiation. So the test should be:
`  ['algebraic_formula', true, 'a**b'],`
          
and not
       ` ['algebraic_formula', false, 'a**b'],`    
So I changed true to false in the version 4.41 that will be released shortly.
And I added a comment explaining that if some users want to be compatible with both old and new browsers they should comment this test.
Note: the `**`  operator is also correct on the php side since php 5.6 so on the server side `**` should be accepted by nearly all servers running Moodle recent versions because of Moodle requirements for php.

**Comment by nadavkav** [comment]
Off Topic...
@jmvedrine , Any chance you are coming to Israel for a visit?

**Comment by jmvedrine** [comment]
Kind offer Nadav, would be cool but there is more than 10 years that I couldn't make any long distance trip and I fear this will also be the same in the future.

**Comment by nadavkav** [comment]
Well... I tried :wink: 
All the best of health! and feel free to change you mind any time in the future.
